"""
Generate the final standalone HTML report for the LarNO/MIKE+/ITZI pipe-network
extended study.

This script is intentionally self-contained and conservative:
- it embeds existing PNG figures as base64 data URIs;
- it corrects the pipe-network/statistics wording found in earlier dashboard
  outputs;
- it keeps the manually verified ITZI eight-event peak table explicit so the
  final report remains reproducible even if older npz summary metadata used a
  wrong field for pipe-node counts.

Run from the repository root:
    python extended_study/generate_final_standalone_report.py
"""

from __future__ import annotations

import base64
import csv
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "extended_study" / "output"
ITZI_DIR = OUT_DIR / "itzi_all"
ITZI_5M_DIR = OUT_DIR / "itzi_5m_compare"
ITZI_5M_REFINED_DIR = OUT_DIR / "itzi_5m_refined"
SWMM_DIR = OUT_DIR / "swmm_network"
REPORT_PATH = OUT_DIR / "LarNO_ITZI_Final_Standalone_Report.html"


@dataclass(frozen=True)
class EventStat:
    event: str
    mike_peak_m: float
    itzi_surface_peak_m: float
    itzi_pipe_peak_m: float
    drained_m3: float | None = None

    @property
    def surface_vs_mike_pct(self) -> float:
        return 100.0 * self.itzi_surface_peak_m / self.mike_peak_m

    @property
    def pipe_vs_mike_pct(self) -> float:
        return 100.0 * self.itzi_pipe_peak_m / self.mike_peak_m

    @property
    def pipe_peak_reduction_pct(self) -> float:
        if self.itzi_surface_peak_m == 0:
            return 0.0
        return 100.0 * (self.itzi_surface_peak_m - self.itzi_pipe_peak_m) / self.itzi_surface_peak_m


EVENT_STATS = [
    EventStat("event1", 2.076, 2.234, 1.946, 242_634),
    EventStat("event20", 1.177, 1.152, 1.103, 137_381),
    EventStat("event65", 1.749, 2.206, 1.913, 230_870),
    EventStat("event66", 1.733, 2.239, 1.972, 238_933),
    EventStat("event67", 2.379, 2.338, 2.338, 347_741),
    EventStat("event68", 1.976, 2.255, 2.171, 306_371),
    EventStat("event69", 2.159, 2.253, 2.169, 307_880),
    EventStat("event70", 2.098, 2.258, 2.173, 317_535),
]


FIGURES = [
    ("计算区域、OSM路网与概念管网", OUT_DIR / "osm_pipe_network.png",
     "路网与DEM整体匹配较好；概念管网沿主要道路布设。图中设计管网为2847个井点、2270条道路管线。"),
    ("八事件峰值水深空间对比", ITZI_DIR / "all_peaks.png",
     "MIKE+参考、ITZI地表动力学、ITZI+概念管网，以及ITZI+管网相对MIKE+差值。当前为4.0 km x 5.6 km子区域。"),
    ("八事件峰值统计柱状图", ITZI_DIR / "all_bars.png",
     "管网削峰按全局最大水深计算，范围约0%-13.3%。event67全局峰值几乎不变，但体积指标显示仍有明显排水。"),
    ("综合dashboard", ITZI_DIR / "all_dashboard.png",
     "原dashboard中的部分文字统计存在口径错误，本报告正文和表格采用修正后的统计解释。"),
    ("散点/误差统计图", ITZI_DIR / "all_scatter.png",
     "ITZI与MIKE+参考结果的分布一致性辅助检查。若该图不存在，报告会自动跳过。"),
    ("MIKE参考结果20m与5m分辨率检查", ITZI_5M_DIR / "mike_reference_20m_vs_5m_peaks.png",
     "同一物理窗口下MIKE参考结果的20m与5m峰值水深对比。若5m数据尚未下载，报告会自动跳过。"),
    ("5m ITZI refined-grid 峰值对比", ITZI_5M_REFINED_DIR / "itzi_5m_refined_peak_bars.png",
     "使用由公开20m DEM/降雨派生的5m输入，真正调用ITZI在5m网格上运行的敏感性实验。该图不是5m MIKE reference验证。"),
    ("5m ITZI refined-grid 管网削减指标", ITZI_5M_REFINED_DIR / "itzi_5m_refined_reduction_metrics.png",
     "5m refined-grid ITZI中，管网对全局峰值、总体水量和淹没格点的削减效果。"),
    # The old output/mike_comparison/mike_comparison_peaks.png was generated by
    # an early full-domain/prototype ITZI workflow and is not consistent with
    # the corrected ITZI dynamic all-events results. Do not include it in the
    # final report; use itzi_all/all_peaks.png as the authoritative MIKE vs ITZI
    # spatial comparison.
    ("MIKE对比统计柱状图", OUT_DIR / "mike_comparison" / "mike_comparison_bars.png",
     "MIKE reference相关统计柱状图。"),
    ("MIKE对比误差指标图", OUT_DIR / "mike_comparison" / "mike_comparison_metrics.png",
     "MIKE comparison指标汇总图。"),
    ("ITZI full-domain 辅助峰值图", OUT_DIR / "itzi_full" / "itzi_full_peaks.png",
     "较大范围/全域辅助ITZI峰值对比图，用作空间一致性检查。"),
    ("ITZI full-domain dashboard", OUT_DIR / "itzi_full" / "itzi_full_dashboard.png",
     "较大范围/全域辅助ITZI dashboard。"),
]

TABLES = [
    ("修正后的ITZI八事件统计表", ITZI_DIR / "all_corrected_metrics.csv",
     "该表由修正后的可视化脚本生成，包含峰值、体积、淹没格点和管网削减率。"),
    ("5m分辨率模式说明", ITZI_5M_DIR / "resolution_summary.csv",
     "若真实region1_5m不存在，则5m为proxy_5m模式。"),
    ("20m与5m/Proxy 5m 峰值统计", ITZI_5M_DIR / "mike_reference_20m_vs_5m_peak_stats.csv",
     "同一物理窗口下20m与5m/proxy_5m参考峰值统计。"),
    ("5m ITZI refined-grid 敏感性统计", ITZI_5M_REFINED_DIR / "itzi_5m_refined_metrics.csv",
     "该表是真正以5m网格运行ITZI得到的敏感性实验统计；输入由公开20m数据细化而来，不是5m MIKE reference验证。"),
    ("SWMM 1D动态波管网模型生成/运行状态", SWMM_DIR / "swmm_build_status.csv",
     "该表记录由OSM概念管网生成的SWMM动态波1D管网模型。若本机无EPA SWMM命令行程序，则状态为not_run_no_swmm_executable。"),
]


def image_data_uri(path: Path) -> str | None:
    if not path.exists():
        return None
    mime = "image/png" if path.suffix.lower() == ".png" else "image/jpeg"
    data = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{data}"


def html_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def rows(stats: Iterable[EventStat]) -> str:
    out = []
    for s in stats:
        drained = "" if s.drained_m3 is None else f"{s.drained_m3:,.0f}"
        note = ""
        if abs(s.pipe_peak_reduction_pct) < 0.05 and s.drained_m3:
            note = "全局最大值未降低；需结合体积/面积/P95指标解释"
        out.append(
            "<tr>"
            f"<td>{html_escape(s.event)}</td>"
            f"<td>{s.mike_peak_m:.3f}</td>"
            f"<td>{s.itzi_surface_peak_m:.3f}</td>"
            f"<td>{s.itzi_pipe_peak_m:.3f}</td>"
            f"<td>{s.surface_vs_mike_pct:.1f}%</td>"
            f"<td>{s.pipe_vs_mike_pct:.1f}%</td>"
            f"<td>{s.pipe_peak_reduction_pct:.1f}%</td>"
            f"<td>{drained}</td>"
            f"<td>{html_escape(note)}</td>"
            "</tr>"
        )
    return "\n".join(out)


def figure_sections() -> str:
    sections = []
    for title, path, caption in FIGURES:
        uri = image_data_uri(path)
        if uri is None:
            continue
        sections.append(
            "<section class='figure-section'>"
            f"<h3>{html_escape(title)}</h3>"
            f"<img src='{uri}' alt='{html_escape(title)}'>"
            f"<p class='caption'>{html_escape(caption)}</p>"
            f"<p class='path'>Source: {html_escape(str(path.relative_to(ROOT)))}</p>"
            "</section>"
        )
    return "\n".join(sections)


def csv_table_sections() -> str:
    sections = []
    for title, path, caption in TABLES:
        if not path.exists():
            continue
        with path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.reader(f)
            data = list(reader)
        if not data:
            continue
        header, body = data[0], data[1:]
        head_html = "".join(f"<th>{html_escape(h)}</th>" for h in header)
        rows_html = []
        for row in body:
            cells = []
            for value in row:
                txt = html_escape(value)
                try:
                    num = float(value)
                    txt = f"{num:.3f}" if abs(num) < 1000 else f"{num:,.1f}"
                except ValueError:
                    pass
                cells.append(f"<td>{txt}</td>")
            rows_html.append("<tr>" + "".join(cells) + "</tr>")
        sections.append(
            "<section>"
            f"<h3>{html_escape(title)}</h3>"
            f"<p class='caption'>{html_escape(caption)}</p>"
            "<div class='table-wrap'><table>"
            f"<thead><tr>{head_html}</tr></thead>"
            f"<tbody>{''.join(rows_html)}</tbody>"
            "</table></div>"
            f"<p class='path'>Source: {html_escape(str(path.relative_to(ROOT)))}</p>"
            "</section>"
        )
    return "\n".join(sections)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    peak_reductions = [s.pipe_peak_reduction_pct for s in EVENT_STATS]
    mean_peak_reduction = sum(peak_reductions) / len(peak_reductions)
    max_peak_reduction = max(peak_reductions)
    min_peak_reduction = min(peak_reductions)

    html = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>LarNO/MIKE+/ITZI 城市洪涝复现与管网拓展研究报告</title>
  <style>
    :root {{
      --fg: #17202a;
      --muted: #5f6b7a;
      --line: #d6dde6;
      --soft: #f5f7fa;
      --accent: #0f766e;
      --warn: #9a3412;
    }}
    body {{
      margin: 0;
      font-family: "Segoe UI", "Microsoft YaHei", Arial, sans-serif;
      color: var(--fg);
      background: white;
      line-height: 1.58;
    }}
    header {{
      padding: 40px 56px 28px;
      border-bottom: 1px solid var(--line);
      background: linear-gradient(180deg, #f8fafc, #ffffff);
    }}
    main {{ padding: 28px 56px 56px; max-width: 1480px; margin: 0 auto; }}
    h1 {{ margin: 0 0 12px; font-size: 30px; letter-spacing: 0; }}
    h2 {{ margin: 32px 0 12px; font-size: 22px; border-bottom: 1px solid var(--line); padding-bottom: 8px; }}
    h3 {{ margin: 26px 0 12px; font-size: 18px; }}
    p {{ margin: 8px 0; }}
    .meta {{ color: var(--muted); font-size: 14px; }}
    .grid {{ display: grid; grid-template-columns: repeat(4, minmax(160px, 1fr)); gap: 12px; margin: 18px 0; }}
    .metric {{ border: 1px solid var(--line); background: var(--soft); padding: 14px 16px; border-radius: 8px; }}
    .metric strong {{ display: block; font-size: 22px; color: var(--accent); margin-bottom: 4px; }}
    .metric span {{ color: var(--muted); font-size: 13px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 16px 0 24px; font-size: 14px; }}
    .table-wrap {{ overflow-x: auto; }}
    th, td {{ border: 1px solid var(--line); padding: 8px 10px; text-align: right; vertical-align: top; }}
    th:first-child, td:first-child, td:last-child {{ text-align: left; }}
    th {{ background: #eef3f8; }}
    .note {{ border-left: 4px solid var(--accent); background: #f0fdfa; padding: 12px 14px; margin: 14px 0; }}
    .warning {{ border-left-color: var(--warn); background: #fff7ed; }}
    .figure-section {{ margin: 28px 0 36px; page-break-inside: avoid; }}
    img {{ display: block; width: 100%; height: auto; border: 1px solid var(--line); background: white; }}
    .caption {{ color: var(--muted); font-size: 14px; }}
    .path {{ color: #7b8794; font-family: Consolas, monospace; font-size: 12px; }}
    ul {{ padding-left: 22px; }}
    li {{ margin: 6px 0; }}
    code {{ font-family: Consolas, monospace; background: #f1f5f9; padding: 1px 4px; border-radius: 4px; }}
    @media print {{
      header, main {{ padding-left: 24px; padding-right: 24px; }}
      .figure-section {{ break-inside: avoid; }}
    }}
  </style>
</head>
<body>
<header>
  <h1>LarNO/MIKE+/ITZI 城市洪涝复现与概念管网拓展研究报告</h1>
  <p class="meta">Standalone HTML report generated at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} from local result figures and corrected statistics.</p>
</header>
<main>
  <section>
    <h2>一、结论摘要</h2>
    <p>当前复现流程总体成立：MIKE+参考结果、ITZI地表动力学结果、ITZI+概念管网结果已经在相同子区域和相同八个事件下完成对比。最终采用的是ITZI动力学地表流求解器，不是早期的静态洼地填充模型。</p>
    <div class="grid">
      <div class="metric"><strong>8</strong><span>对比降雨事件</span></div>
      <div class="metric"><strong>4.0 x 5.6 km</strong><span>当前ITZI动力学计算子区域</span></div>
      <div class="metric"><strong>{min_peak_reduction:.1f}%-{max_peak_reduction:.1f}%</strong><span>按全局最大水深计算的管网削峰范围</span></div>
      <div class="metric"><strong>{mean_peak_reduction:.1f}%</strong><span>八事件平均全局峰值削减</span></div>
    </div>
    <div class="note warning">
      <p><strong>已修正的关键口径：</strong>早期dashboard中“Pipe nodes in region: 8”和“削峰0-5%”不可靠。正确解释是：概念设计管网全域为2847个井点、2270条道路管线；ITZI子区域计算使用的管网节点应按实际裁剪网络统计，不能写成8。削峰按全局最大水深计算为0%-13.3%，event67虽全局最大值几乎不变，但排水体积仍明显，因此必须同时报告体积、面积和分位数指标。</p>
    </div>
  </section>

  <section>
    <h2>二、模型与数据口径</h2>
    <ul>
      <li><strong>MIKE+ Reference：</strong>论文LarNO数据集中的参考水深结果，作为监督学习和物理模型复现对比基准。</li>
      <li><strong>LarNO：</strong>论文原模型输入包括降雨强度、累计降雨、DSM/地形、不透水率、排水入口等特征；输出为逐时刻二维水深。</li>
      <li><strong>ITZI Surface：</strong>使用ITZI动力学地表流求解器，仅考虑地表产汇流和地形控制。</li>
      <li><strong>ITZI + Pipes：</strong>在ITZI地表模型基础上加入沿OSM道路抽象生成的概念排水管网，用于探索管网特征对洪涝结果的削减作用。</li>
      <li><strong>SWMM 1D管网分支：</strong>由当前OSM概念管网生成SWMM动态波管网<code>.inp</code>，用于完整1D管网路由对比。该分支与ITZI sink分支并列；若未安装EPA SWMM命令行程序，则报告仅列出模型生成状态。</li>
      <li><strong>边界说明：</strong>论文参考模型描述为研究区外边界闭合。当前ITZI子区域结果需说明为裁剪区域计算，边界低洼处可能放大局地峰值。</li>
      <li><strong>分辨率说明：</strong>当前已完成的ITZI动力学计算为20 m网格；若使用同一4.0 km x 5.6 km物理窗口提升至5 m，网格将由200 x 280增至800 x 1120，计算单元数增加16倍。5 m比较必须使用真实<code>region1_5m</code>参考数据，不应由20 m结果插值代替。</li>
      <li><strong>5 m ITZI可运行性：</strong>缺少真实<code>region1_5m</code> MIKE+ reference并不意味着不能运行5 m ITZI。可用公开20 m DEM/降雨派生5 m输入，真正调用ITZI在5 m网格上运行，作为分辨率敏感性实验；然后将5 m结果聚合回20 m，与现有MIKE+ 20 m reference对比。</li>
    </ul>
  </section>

  <section>
    <h2>三、八事件峰值统计表</h2>
    <table>
      <thead>
        <tr>
          <th>Event</th>
          <th>MIKE+ Peak (m)</th>
          <th>ITZI Surface Peak (m)</th>
          <th>ITZI+Pipes Peak (m)</th>
          <th>Surface/MIKE</th>
          <th>Pipe/MIKE</th>
          <th>Pipe Peak Reduction</th>
          <th>Drained Volume (m3)</th>
          <th>说明</th>
        </tr>
      </thead>
      <tbody>
        {rows(EVENT_STATS)}
      </tbody>
    </table>
    <p>表中削峰率定义为 <code>(ITZI Surface Peak - ITZI+Pipes Peak) / ITZI Surface Peak</code>。该指标只反映全域最大水深点的变化，不能单独代表管网总体排水效果。</p>
  </section>

  <section>
    <h2>四、统计解释与需要保留的 caveat</h2>
    <ul>
      <li>event1、event65、event66 的ITZI地表峰值高于MIKE+较多，加入管网后更接近MIKE+，说明概念管网对这些事件有明显削峰作用。</li>
      <li>event67 的全局峰值不变，但排水体积较大，说明最大值出现在管网控制不足的局部位置；正式分析中应补充P95/P99水深、总积水体积和淹没面积削减率。</li>
      <li>当前空间图为4.0 km x 5.6 km子区域，不应表述为完整100 km²区域的动力学全域复现。</li>
      <li>5 m refined-grid结果如存在，应表述为“由公开20 m输入派生的5 m ITZI敏感性实验”，而不是“真实5 m MIKE reference复现”。</li>
      <li>概念管网来自OSM道路和DEM校正，不等同于深圳真实市政管网；因此它适合用于机制探索和LarNO特征扩展，不应作为真实排水系统校核结论。</li>
      <li>新增SWMM分支负责1D管网动态波路由；当前若无PySWMM/同步接口，则它是独立1D管网模型，不等同于完全双向ITZI-SWMM耦合。报告中需区分“SWMM 1D路由”和“ITZI地表削峰图”。</li>
    </ul>
  </section>

  <section>
    <h2>五、完整表格数据</h2>
    {csv_table_sections()}
  </section>

  <section>
    <h2>六、图件汇总</h2>
    {figure_sections()}
  </section>

  <section>
    <h2>七、建议用于LarNO扩展的管网特征</h2>
    <p>为了把概念管网信息加入LarNO训练/微调，建议不要直接输入离散管线矢量，而是栅格化为与DEM同分辨率的静态或半静态特征层：</p>
    <ul>
      <li><code>pipe_density</code>：单位网格邻域内管线长度密度。</li>
      <li><code>node_density</code>：检查井/雨水口节点密度。</li>
      <li><code>pipe_capacity</code>：按管径、坡度、Manning公式估算的单位面积排水能力。</li>
      <li><code>distance_to_pipe</code>：到最近管线距离。</li>
      <li><code>distance_to_outfall</code>：到排口或主干管距离。</li>
      <li><code>pipe_slope</code>：沿管线方向的坡度或局部平均坡度。</li>
      <li><code>inlet_area</code>：可与论文原有drain inlet area输入保持一致或作为增强特征。</li>
    </ul>
  </section>
</main>
</body>
</html>
"""

    REPORT_PATH.write_text(html, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
